### ISSUE TITLE
Data issue

### ISSUE THREAD

**Issue by Srilatha100** [ahwelgemoed/calendar-native-widget#2]
Hi,
I just followed documentation & done the mentioned logics & settings same as it is in screenshots & doc. I can able to see the Calendar and after clicking date, opening new page & saving the name & description data's and committing the calendar object. But the saved event information's are not showing in my calendar. Even i added microflow by retrieving the Calendar data from db, it's just empty on click of save button itself. PFA :
![image](https://user-images.githubusercontent.com/62939455/103792366-8ea68d00-5069-11eb-97b2-f203dd637dd3.png)
![image](https://user-images.githubusercontent.com/62939455/103792404-9bc37c00-5069-11eb-9db8-64f04d24c5d1.png)
![image](https://user-images.githubusercontent.com/62939455/103792434-a67e1100-5069-11eb-9050-322f998938a4.png)
![image](https://user-images.githubusercontent.com/62939455/103792484-b269d300-5069-11eb-8a2a-ae4631707de7.png)
![image](https://user-images.githubusercontent.com/62939455/103792692-d4635580-5069-11eb-89d0-b8c36cfdcead.png)
![image](https://user-images.githubusercontent.com/62939455/103792825-dd542700-5069-11eb-8e97-2f0faba04c91.png)

Any idea on this?

Any help will be appreciated.

**Comment by ahwelgemoed** [comment]
Hi @Srilatha100 

Sure I will be able to help. I will work on this in the morning and let you know.

**Comment by Srilatha100** [comment]
Thank you so much, for immediate reply. Looking for this fix ASAP.

**Comment by ahwelgemoed** [comment]
Hey @Srilatha100 

This morning I created a new Project with the Widget in it and all seemed fine. I did have to restart Mendix Make it Native App sometimes as it seems to have a bug where it "keeps" data for a couple of refreshes. 

I did extract the logic into a separate `.mpk` file. If you want I can email it to you and you will be able to see my implementation.

I also added some images to the docs.

**Comment by Srilatha100** [comment]
Hi,

I have downloaded the widget in chrome and added it into the Widgets directory of application. Will it make difference like rather than direct download in Mendix application ? 

If you can share that mpk, that works for me. I will have a look into that once. 

 

Regards,

Srilatha

**Comment by Srilatha100** [comment]
Hi,

I have downloaded the widget in chrome and added it into the Widgets directory of application. Will it make difference like rather than direct download in Mendix application ?

If you can share that mpk, that works for me. I will have a look into that once.

Regards,
Srilatha

**Comment by Srilatha100** [comment]
> Hey @Srilatha100
> 
> This morning I created a new Project with the Widget in it and all seemed fine. I did have to restart Mendix Make it Native App sometimes as it seems to have a bug where it "keeps" data for a couple of refreshes.
> 
> I did extract the logic into a separate `.mpk` file. If you want I can email it to you and you will be able to see my implementation.
> 
> I also added some images to the docs.

**Comment by Srilatha100** [comment]
> Hi,
> 
> I have downloaded the widget in chrome and added it into the Widgets directory of application. Will it make difference like rather than direct download in Mendix application ?
> 
> If you can share that mpk, that works for me. I will have a look into that once.
> 
> Regards,
> Srilatha

**Comment by Srilatha100** [comment]
> > Hey @Srilatha100
> > This morning I created a new Project with the Widget in it and all seemed fine. I did have to restart Mendix Make it Native App sometimes as it seems to have a bug where it "keeps" data for a couple of refreshes.
> > I did extract the logic into a separate `.mpk` file. If you want I can email it to you and you will be able to see my implementation.
> > I also added some images to the docs.

**Comment by Srilatha100** [comment]
Hi,

I have downloaded the widget in chrome and added it into the Widgets directory of application. Will it make difference like rather than direct download in Mendix application ?

If you can share that mpk, that works for me. I will have a look into that once.

Regards,
Srilatha
