### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by MartijnBooijAppronto** [ahwelgemoed/calendar-native-widget#3]
Hi.  I'm getting React error "Invalid time value". In the project we want to show birthdays on the calendar, so we need to get the actual birthdate (non localized) and change the actual birth year with the current year. So, after some manipulation the dates are successfully created and passed on the widget. When rendering the widget, the error occurs. In my client logging I can see that the dates are actual dates. I tried it both with non localized dates (did not set the time elements) and localized dates (parseDateTime and parseDateTimeUTC with "10:00" as time element). Any help is appreciated, thanks. Local log is not giving me any clue.

**Comment by ahwelgemoed** [comment]
Hi - Thanks for the issue. Is it possible to get some screenshots of what the console is logging out and how you are getting to that "parsed" dates. 

I will have to try and replicate the error, so as many screenshots as you can possibly share for me to recreate it as accurately as possible is appreciated.

Also what Mendix version you are using.

Thanks!

**Comment by MartijnBooijAppronto** [comment]
Hi Arno

We have an employee table:

[cid:image001.png@01D6F885.853BB5B0]

DateOfBirth is non localized date

[cid:image002.png@01D6F885.853BB5B0]

Month_DateOfBirth and Day_DateOfBirth are set in an event handler (BCo):

[cid:image004.png@01D6F885.EE83C440]

When processing the birth days in a nanoflow, all employees that have a birthday in the -3 / +3 date range are being selected:
[cid:image006.png@01D6F886.45CDF540]

[cid:image007.png@01D6F886.45CDF540]


[cid:image005.png@01D6F885.EE83C440]



The found records are then processed to create the calendar data. If an employee birth date is 29th of January 1981, we want to set the calendar date to 29th of January 2021 (current year) in order to be able to present it in the calendar.

[cid:image008.png@01D6F888.7D8B9A30]

These are the steps where the rendering takes place:
[cid:image009.png@01D6F888.7D8B9A30]


[cid:image010.png@01D6F888.F69B4560]

[cid:image011.png@01D6F888.F69B4560]

[cid:image012.png@01D6F888.F69B4560]


I tested also with instead of $BirthDate in above create statement, the following: addDays([%BeginOfCurrentDay%],-1) but that also failed.

Hope this helps. Thanks for your quick reply btw.


_________________________

[logo-appronto]<https://www.appronto.nl/>

**Comment by MartijnBooijAppronto** [comment]
The error logging:

01-28 10:38:57.275  7855 30406 I ReactNativeJS: Showing 4 birthdays
01-28 10:38:57.280  7855 30406 D ReactNativeJS: 'Received 4 objects for widget Core_Native.Birthday_Calendar.calendarNativeWidget1', 'object ids:', [ 'GUID:id_gts_30',
01-28 10:38:57.280  7855 30406 D ReactNativeJS:   'GUID:id_gts_31',
01-28 10:38:57.280  7855 30406 D ReactNativeJS:   'GUID:id_gts_33',
01-28 10:38:57.280  7855 30406 D ReactNativeJS:   'GUID:id_gts_34' ]
01-28 10:38:57.531  7855 30406 E ReactNativeJS: RangeError: Invalid time value
01-28 10:38:57.531  7855 30406 E ReactNativeJS:
01-28 10:38:57.531  7855 30406 E ReactNativeJS: This error is located at:
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Y
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in t
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in t
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in pluginWidget(t)
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in pluginWidget()
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in pluginWidget()
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTScrollView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in N
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in withNavigationScrolling(N)
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in withNavigation(withNavigationScrolling(N))
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in NavigationAwareScrollable(N)
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in pluginWidget()
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RootStoreProvider
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in ru
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in r
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in ForwardRef
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in PanGestureHandler
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in H
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in E
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in b
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in x
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in c
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in C
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in k
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in ForwardRef
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in PanGestureHandler
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in H
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in E
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in b
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in x
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in c
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in AnimatedComponent(Component)
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in AnimatedComponent(Component)
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in PanGestureHandler
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in le
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in L
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in ForwardRef
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in PanGestureHandler
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in P
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in H
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in E
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in b
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RNCSafeAreaView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in GestureHandlerRootView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in x
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in Unknown
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in TopLevelView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in n
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in a
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.531  7855 30406 E ReactNativeJS:     in x
01-28 10:38:57.549  7855 30406 E ReactNativeJS: RangeError: Invalid time value
01-28 10:38:57.549  7855 30406 E ReactNativeJS:
01-28 10:38:57.549  7855 30406 E ReactNativeJS: This error is located at:
01-28 10:38:57.549  7855 30406 E ReactNativeJS:     in O
01-28 10:38:57.549  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.549  7855 30406 E ReactNativeJS:     in TopLevelView
01-28 10:38:57.549  7855 30406 E ReactNativeJS:     in n
01-28 10:38:57.549  7855 30406 E ReactNativeJS:     in a
01-28 10:38:57.549  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.549  7855 30406 E ReactNativeJS:     in RCTView
01-28 10:38:57.549  7855 30406 E ReactNativeJS:     in x
01-28 10:38:57.557  7855 30406 E ReactNativeJS: 'Invalid time value', 'default@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:1260:566190\nhttp://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:1260:808511\nmap@[native code]\nre@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:1260:808415\nhttp://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:1260:809091\nIi@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:57557\njl@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:78298\njl@[native code]\nunstable_runWithPriority@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:176:3915\nUl@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:66814\nUl@[native code]\nPl@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:65839\nPl@[native code]\nhttp://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:25495\nunstable_runWithPriority@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:176:3915\nsn@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:25442\ncn@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:25377\n_e@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:88686\nNe@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:13582\nUe@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:13755\nreceiveEvent@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:101:14164\nvalue@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:54:3685\nhttp://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:54:841\nvalue@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:54:2939\nvalue@http://192.168.178.34:8083/index.bundle?platform=android&dev=false&minify=true:54:813\nvalue@[native code]'


Hi - Thanks for the issue. Is it possible to get some screenshots of what the console is logging out and how you are getting to that "parsed" dates.

I will have to try and replicate the error, so as many screenshots as you can possibly share for me to recreate it as accurately as possible is appreciated.

Also what Mendix version you are using.

Thanks!

**Comment by MartijnBooijAppronto** [comment]
Running Mx 8.17.0


Hi - Thanks for the issue. Is it possible to get some screenshots of what the console is logging out and how you are getting to that "parsed" dates.

I will have to try and replicate the error, so as many screenshots as you can possibly share for me to recreate it as accurately as possible is appreciated.

Also what Mendix version you are using.

Thanks!

**Comment by ahwelgemoed** [comment]
Thanks - unfortunately, I can't see the images. Could you try and resend to `arno.welgemoed [at] mendix.com`

**Comment by jorisvdinther** [comment]
Following this thread because we've got the exact same error in Mendix 8.17.
I open the native app in the Mendix Make It Native app.

When I start the app without debug mode the app crashes on 'invalid time value' error
When I start the app with debug mode the app crashes on 'invalid time value' error
When I start the app with debug mode and I enable remote JS debugging the app won't crash and displays the items

**Comment by ahwelgemoed** [comment]
@jorisvdinther A new version of the app has been pushed to the Store `V1.0.3` that seems to fix @MartijnBooijAppronto issue. Could you try with that Version. If your issue continues please feel free to open a new issue.

**Comment by MartijnBooijAppronto** [comment]
Hi Arno

Just implemented the updated version and it is okay!

Thanks for your help.

Met vriendelijke groet,

Martijn Booij
